-- Carga los permisos nuevos del catalogo (src/utils/permissions.ts) en la matriz.
--
-- Cada rol recibe exactamente los accesos que hoy obtiene por nombre de rol, de modo que
-- al reemplazar esas comprobaciones por permisos nadie pierda acceso. Solo agrega filas
-- (ON CONFLICT DO NOTHING), asi que respeta cualquier ajuste manual hecho en la matriz.
--
-- Ajustes sobre permisos existentes, decididos al revisar la matriz vigente:
--   * jefe + VIEW_ALL_TEAM_STATS: hoy ve la actividad de todo el equipo por ser jefe.
--   * jefe - MANAGE_DISPATCH: el despacho del jefe se mantiene como hoy (sin modulo de despacho).
--   * facturador/tesorero - VIEW_OPERATIONS: Operaciones se mantiene solo para admin y jefe.
--     El permiso no se usaba en ninguna parte, por lo que quitarlo no cambia nada hoy.

INSERT INTO public.role_permissions (role, permission)
VALUES
    ('admin', 'VIEW_CLIENTS'),
    ('admin', 'ASSIGN_CLIENTS'),
    ('admin', 'MANAGE_CLIENT_CREDIT'),
    ('admin', 'MANAGE_DISCOUNT_POLICY'),
    ('admin', 'MERGE_CLIENTS'),
    ('admin', 'VIEW_QUOTATIONS'),
    ('admin', 'VIEW_ALL_QUOTATIONS'),
    ('admin', 'ASSIGN_QUOTATION_SELLER'),
    ('admin', 'CONVERT_ANY_QUOTATION'),
    ('admin', 'EDIT_QUOTE_PRICES'),
    ('admin', 'BYPASS_DISCOUNT_LIMIT'),
    ('admin', 'SIMULATE_LOCATION'),
    ('admin', 'VIEW_AUDIT_TRACE'),
    ('admin', 'VIEW_ALL_ORDERS'),
    ('admin', 'RESEND_ORDER_EMAIL'),
    ('admin', 'CANCEL_ORDERS'),
    ('admin', 'MANAGE_COURIER_SHIPMENTS'),
    ('admin', 'VIEW_SCHEDULE'),
    ('admin', 'VIEW_VISITS'),
    ('admin', 'CONVERT_COLD_VISITS'),
    ('admin', 'VIEW_MAP'),
    ('admin', 'VIEW_PIPELINE'),
    ('admin', 'SEND_TEAM_PUSH'),
    ('admin', 'VIEW_LEADS'),
    ('admin', 'VIEW_ALL_LEADS'),
    ('admin', 'MANAGE_LEAD_TEMPLATES'),
    ('admin', 'VIEW_META_LEADS'),
    ('admin', 'VIEW_COLLECTIONS'),
    ('admin', 'VIEW_ALL_COLLECTIONS'),
    ('admin', 'COMMENT_COLLECTIONS'),
    ('admin', 'VIEW_INVENTORY'),
    ('admin', 'VIEW_INVENTORY_VALUE'),
    ('admin', 'VIEW_INVENTORY_ANALYTICS'),
    ('admin', 'MANAGE_STOCKLESS_SALES'),
    ('admin', 'DOWNLOAD_CATALOG'),
    ('admin', 'MANAGE_WEB_STORE'),
    ('admin', 'RECEIVE_IMPORTS'),
    ('admin', 'SEND_PURCHASE_ORDER_EMAIL'),
    ('admin', 'VIEW_DELIVERY_STATUS'),
    ('admin', 'MANAGE_SALES_FLOW'),
    ('admin', 'MANAGE_INTEGRATIONS'),
    ('jefe', 'VIEW_CLIENTS'),
    ('jefe', 'ASSIGN_CLIENTS'),
    ('jefe', 'MANAGE_CLIENT_CREDIT'),
    ('jefe', 'MERGE_CLIENTS'),
    ('jefe', 'VIEW_QUOTATIONS'),
    ('jefe', 'VIEW_ALL_QUOTATIONS'),
    ('jefe', 'EDIT_QUOTE_PRICES'),
    ('jefe', 'BYPASS_DISCOUNT_LIMIT'),
    ('jefe', 'VIEW_ALL_ORDERS'),
    ('jefe', 'CANCEL_ORDERS'),
    ('jefe', 'MANAGE_COURIER_SHIPMENTS'),
    ('jefe', 'VIEW_SCHEDULE'),
    ('jefe', 'VIEW_VISITS'),
    ('jefe', 'CONVERT_COLD_VISITS'),
    ('jefe', 'VIEW_MAP'),
    ('jefe', 'VIEW_PIPELINE'),
    ('jefe', 'SEND_TEAM_PUSH'),
    ('jefe', 'VIEW_LEADS'),
    ('jefe', 'VIEW_ALL_LEADS'),
    ('jefe', 'MANAGE_LEAD_TEMPLATES'),
    ('jefe', 'VIEW_COLLECTIONS'),
    ('jefe', 'VIEW_ALL_COLLECTIONS'),
    ('jefe', 'VIEW_INVENTORY'),
    ('jefe', 'VIEW_INVENTORY_VALUE'),
    ('jefe', 'VIEW_INVENTORY_ANALYTICS'),
    ('jefe', 'DOWNLOAD_CATALOG'),
    ('jefe', 'VIEW_DELIVERY_STATUS'),
    ('bodega', 'VIEW_CLIENTS'),
    ('bodega', 'VIEW_QUOTATIONS'),
    ('bodega', 'EDIT_QUOTE_PRICES'),
    ('bodega', 'BYPASS_DISCOUNT_LIMIT'),
    ('bodega', 'VIEW_SCHEDULE'),
    ('bodega', 'VIEW_VISITS'),
    ('bodega', 'VIEW_MAP'),
    ('bodega', 'VIEW_PIPELINE'),
    ('bodega', 'VIEW_COLLECTIONS'),
    ('bodega', 'VIEW_ALL_COLLECTIONS'),
    ('bodega', 'VIEW_INVENTORY'),
    ('bodega', 'VIEW_INVENTORY_VALUE'),
    ('bodega', 'MANAGE_STOCKLESS_SALES'),
    ('bodega', 'SEND_PURCHASE_ORDER_EMAIL'),
    ('facturador', 'VIEW_CLIENTS'),
    ('facturador', 'MANAGE_CLIENT_CREDIT'),
    ('facturador', 'MERGE_CLIENTS'),
    ('facturador', 'VIEW_QUOTATIONS'),
    ('facturador', 'VIEW_ALL_QUOTATIONS'),
    ('facturador', 'ASSIGN_QUOTATION_SELLER'),
    ('facturador', 'CONVERT_ANY_QUOTATION'),
    ('facturador', 'EDIT_QUOTE_PRICES'),
    ('facturador', 'BYPASS_DISCOUNT_LIMIT'),
    ('facturador', 'VIEW_ALL_ORDERS'),
    ('facturador', 'RESEND_ORDER_EMAIL'),
    ('facturador', 'CANCEL_ORDERS'),
    ('facturador', 'MANAGE_COURIER_SHIPMENTS'),
    ('facturador', 'VIEW_SCHEDULE'),
    ('facturador', 'CONVERT_COLD_VISITS'),
    ('facturador', 'VIEW_COLLECTIONS'),
    ('facturador', 'VIEW_ALL_COLLECTIONS'),
    ('facturador', 'COMMENT_COLLECTIONS'),
    ('facturador', 'VIEW_INVENTORY'),
    ('facturador', 'VIEW_INVENTORY_VALUE'),
    ('facturador', 'MANAGE_INTEGRATIONS'),
    ('tesorero', 'VIEW_CLIENTS'),
    ('tesorero', 'ASSIGN_CLIENTS'),
    ('tesorero', 'MERGE_CLIENTS'),
    ('tesorero', 'VIEW_QUOTATIONS'),
    ('tesorero', 'VIEW_ALL_QUOTATIONS'),
    ('tesorero', 'ASSIGN_QUOTATION_SELLER'),
    ('tesorero', 'EDIT_QUOTE_PRICES'),
    ('tesorero', 'BYPASS_DISCOUNT_LIMIT'),
    ('tesorero', 'VIEW_ALL_ORDERS'),
    ('tesorero', 'RESEND_ORDER_EMAIL'),
    ('tesorero', 'CANCEL_ORDERS'),
    ('tesorero', 'MANAGE_COURIER_SHIPMENTS'),
    ('tesorero', 'VIEW_SCHEDULE'),
    ('tesorero', 'CONVERT_COLD_VISITS'),
    ('tesorero', 'VIEW_COLLECTIONS'),
    ('tesorero', 'VIEW_ALL_COLLECTIONS'),
    ('tesorero', 'COMMENT_COLLECTIONS'),
    ('tesorero', 'VIEW_INVENTORY'),
    ('tesorero', 'VIEW_INVENTORY_VALUE'),
    ('tesorero', 'MANAGE_INTEGRATIONS'),
    ('seller', 'VIEW_CLIENTS'),
    ('seller', 'VIEW_QUOTATIONS'),
    ('seller', 'VIEW_SCHEDULE'),
    ('seller', 'VIEW_VISITS'),
    ('seller', 'CONVERT_COLD_VISITS'),
    ('seller', 'VIEW_MAP'),
    ('seller', 'VIEW_PIPELINE'),
    ('seller', 'VIEW_LEADS'),
    ('seller', 'VIEW_META_LEADS'),
    ('seller', 'VIEW_COLLECTIONS'),
    ('seller', 'COMMENT_COLLECTIONS'),
    ('seller', 'VIEW_INVENTORY'),
    ('seller', 'VIEW_DELIVERY_STATUS'),
    ('jefe', 'VIEW_ALL_TEAM_STATS')
ON CONFLICT (role, permission) DO NOTHING;

DELETE FROM public.role_permissions
WHERE (role = 'jefe' AND permission = 'MANAGE_DISPATCH')
   OR (role IN ('facturador', 'tesorero', 'supervisor') AND permission = 'VIEW_OPERATIONS');

NOTIFY pgrst, 'reload schema';
